#!/bin/sh

# add modified files to commit message
# should not be triggered for merge commits

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ -z "$COMMIT_SOURCE" ]; then
    printf "\n\n# --- Modified files ---\n" >> "$COMMIT_MSG_FILE"
    git diff --cached --name-only >> "$COMMIT_MSG_FILE"
fi